// /*
//  * This source file was generated by the Gradle 'init' task
//  */

package final_proyek_pbo;

import final_proyek_pbo.view.LandingView;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class App extends Application {

    @Override
    public void start(Stage primaryStage) {
        LandingView landing = new LandingView();

Scene scene = new Scene(
        landing.getView(),
        1200,
        700);

primaryStage.setTitle("PINISI");
primaryStage.setScene(scene);
primaryStage.show();



    }

    public static void main(String[] args) {
        launch(args);
    }
}